name: 'Scan Dockerfile Changes for CVE Differences'
description: 'Detects changed Dockerfiles via git diff and scans old vs new images for CVE comparison'

runs:
  using: 'composite'
  steps:
    - name: Detect Changed Dockerfiles and Scan CVEs
      shell: bash
      run: |
        set -euo pipefail
        
        # Function to output to both console and summary
        output() {
          echo "$@"
          echo "$@" >> $GITHUB_STEP_SUMMARY
        }
        
        output "# 📊 CVE Comparison Report"
        output ""
        
        # Check if there are any changes
        if ! git diff --quiet HEAD; then
          output "✅ Changes detected, analyzing..."
        else
          output "ℹ️ No changes detected"
          exit 0
        fi
        
        # Install grype if needed
        if ! command -v grype &> /dev/null; then
          output "📥 Installing Grype..."
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b "${GITHUB_WORKSPACE}/bin"
          export PATH="${GITHUB_WORKSPACE}/bin:$PATH"
        fi
        
        # Find all changed Dockerfiles
        CHANGED_FILES=$(git diff --name-only HEAD | grep -E '(Dockerfile|\.Dockerfile)$' || true)
        
        if [ -z "$CHANGED_FILES" ]; then
          output "ℹ️ No Dockerfile changes found"
          exit 0
        fi
        
        output "📦 Changed Dockerfiles:"
        output '```'
        output "$CHANGED_FILES"
        output '```'
        output ""
        
        # Process each Dockerfile
        while IFS= read -r dockerfile; do
          [ -z "$dockerfile" ] && continue
          
          output "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          output "🔍 Processing: $dockerfile"
          output "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          output ""
          
          # Get the diff for this Dockerfile
          DIFF_OUTPUT=$(git diff HEAD -- "$dockerfile")
          
          if [ -z "$DIFF_OUTPUT" ]; then
            output "⚠️ No diff content found for $dockerfile"
            continue
          fi
          
          # Extract the old and new FROM lines
          OLD_FROM=$(echo "$DIFF_OUTPUT" | grep "^-FROM " | head -n1 | sed 's/^-FROM //')
          NEW_FROM=$(echo "$DIFF_OUTPUT" | grep "^+FROM " | head -n1 | sed 's/^\+FROM //')
          
          if [ -z "$OLD_FROM" ] || [ -z "$NEW_FROM" ]; then
            output "⚠️ Could not extract FROM lines from diff for $dockerfile"
            continue
          fi
          
          output "🔄 Change detected:"
          output "  **Old:** \`$OLD_FROM\`"
          output "  **New:** \`$NEW_FROM\`"
          output ""
          
          if [ "$OLD_FROM" = "$NEW_FROM" ]; then
            output "ℹ️ No FROM line changes"
            continue
          fi
          
          output "| Aspect | Details |"
          output "|--------|---------|"
          output "| **Before** | \`$OLD_FROM\` |"
          output "| **After**  | \`$NEW_FROM\` |"
          output ""
          
          # Pull and scan old image
          output "🔍 Scanning old image..."
          docker pull "$OLD_FROM" >/dev/null 2>&1 || { output "❌ Failed to pull $OLD_FROM"; continue; }
          OLD_SCAN=$(grype "$OLD_FROM" -o json -q 2>/dev/null)
          
          # Parse old CVE counts
          OLD_CRITICAL=$(echo "$OLD_SCAN" | jq '[.matches[] | select(.vulnerability.severity == "Critical")] | length')
          OLD_HIGH=$(echo "$OLD_SCAN" | jq '[.matches[] | select(.vulnerability.severity == "High")] | length')
          OLD_MEDIUM=$(echo "$OLD_SCAN" | jq '[.matches[] | select(.vulnerability.severity == "Medium")] | length')
          OLD_LOW=$(echo "$OLD_SCAN" | jq '[.matches[] | select(.vulnerability.severity == "Low")] | length')
          OLD_NEGLIGIBLE=$(echo "$OLD_SCAN" | jq '[.matches[] | select(.vulnerability.severity == "Negligible")] | length')
          OLD_UNKNOWN=$(echo "$OLD_SCAN" | jq '[.matches[] | select(.vulnerability.severity == "Unknown")] | length')
          OLD_TOTAL=$(echo "$OLD_SCAN" | jq '.matches | length')
          
          # Pull and scan new image
          output "🔍 Scanning new image..."
          docker pull "$NEW_FROM" >/dev/null 2>&1 || { output "❌ Failed to pull $NEW_FROM"; continue; }
          NEW_SCAN=$(grype "$NEW_FROM" -o json -q 2>/dev/null)
          
          # Parse new CVE counts
          NEW_CRITICAL=$(echo "$NEW_SCAN" | jq '[.matches[] | select(.vulnerability.severity == "Critical")] | length')
          NEW_HIGH=$(echo "$NEW_SCAN" | jq '[.matches[] | select(.vulnerability.severity == "High")] | length')
          NEW_MEDIUM=$(echo "$NEW_SCAN" | jq '[.matches[] | select(.vulnerability.severity == "Medium")] | length')
          NEW_LOW=$(echo "$NEW_SCAN" | jq '[.matches[] | select(.vulnerability.severity == "Low")] | length')
          NEW_NEGLIGIBLE=$(echo "$NEW_SCAN" | jq '[.matches[] | select(.vulnerability.severity == "Negligible")] | length')
          NEW_UNKNOWN=$(echo "$NEW_SCAN" | jq '[.matches[] | select(.vulnerability.severity == "Unknown")] | length')
          NEW_TOTAL=$(echo "$NEW_SCAN" | jq '.matches | length')
          
          # Calculate differences
          TOTAL_DIFF=$((NEW_TOTAL - OLD_TOTAL))
          CRITICAL_DIFF=$((NEW_CRITICAL - OLD_CRITICAL))
          HIGH_DIFF=$((NEW_HIGH - OLD_HIGH))
          MEDIUM_DIFF=$((NEW_MEDIUM - OLD_MEDIUM))
          LOW_DIFF=$((NEW_LOW - OLD_LOW))
          NEGLIGIBLE_DIFF=$((NEW_NEGLIGIBLE - OLD_NEGLIGIBLE))
          UNKNOWN_DIFF=$((NEW_UNKNOWN - OLD_UNKNOWN))
          
          # Format difference helper
          format_diff() {
            local old=$1
            local new=$2
            local diff=$3
            if [ $diff -gt 0 ]; then
              echo "$old → $new 🔴 (+$diff)"
            elif [ $diff -lt 0 ]; then
              echo "$old → $new 🟢 ($diff)"
            else
              echo "$old → $new ⚪ (0)"
            fi
          }
          
          output "### CVE Counts by Severity"
          output ""
          output "| Severity | Change |"
          output "|----------|--------|"
          output "| Critical | $(format_diff $OLD_CRITICAL $NEW_CRITICAL $CRITICAL_DIFF) |"
          output "| High     | $(format_diff $OLD_HIGH $NEW_HIGH $HIGH_DIFF) |"
          output "| Medium   | $(format_diff $OLD_MEDIUM $NEW_MEDIUM $MEDIUM_DIFF) |"
          output "| Low      | $(format_diff $OLD_LOW $NEW_LOW $LOW_DIFF) |"
          output "| Negligible | $(format_diff $OLD_NEGLIGIBLE $NEW_NEGLIGIBLE $NEGLIGIBLE_DIFF) |"
          output "| Unknown  | $(format_diff $OLD_UNKNOWN $NEW_UNKNOWN $UNKNOWN_DIFF) |"
          output "| **Total** | **$(format_diff $OLD_TOTAL $NEW_TOTAL $TOTAL_DIFF)** |"
          output ""
          
          # Assessment
          if [ $TOTAL_DIFF -lt 0 ]; then
            output "### ✅ Assessment: IMPROVEMENT"
            output "Reduces CVE count by $((-TOTAL_DIFF))"
          elif [ $TOTAL_DIFF -gt 0 ]; then
            output "### ⚠️ Assessment: REGRESSION"
            output "Increases CVE count by $TOTAL_DIFF"
          else
            output "### ⚪ Assessment: NO CHANGE"
          fi
          
          CRITICAL_HIGH_DIFF=$((CRITICAL_DIFF + HIGH_DIFF))
          if [ $CRITICAL_HIGH_DIFF -lt 0 ]; then
            output ""
            output "**🎉 Critical/High CVEs reduced by $((-CRITICAL_HIGH_DIFF))**"
          elif [ $CRITICAL_HIGH_DIFF -gt 0 ]; then
            output ""
            output "**⚠️ Critical/High CVEs increased by $CRITICAL_HIGH_DIFF**"
          fi
          
          output ""
        done
        
        output "---"
        output ""
        output "✅ CVE comparison complete"
